### ISSUE TITLE
AccessControlListNotSupported error on simple deploment

### ISSUE THREAD

**Issue by tomliptrot** [bitovi/github-actions-deploy-docker-to-ec2#128]
On running this action with basic settings I'm getting an `AccessControlListNotSupported` error and am not sure how to fix it.

My deploy.yaml is:
```
name: Basic deploy
on:
  push:
    branches: [ main ]

jobs:
  EC2-Deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
      url: ${{ steps.deploy.outputs.vm_url }}
    steps:
      - id: deploy
        uses: bitovi/github-actions-deploy-docker-to-ec2@v0.5.0
        with:
          aws_access_key_id: ${{ secrets.ACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.SECRET_KEY }}
          aws_default_region: eu-west-2
          app_port: 80
```

And the error I get is this:

```
 aws_elb.vm[0]: Creation complete after 5s [id=tomliptrot-ecr-test-main]
  ╷
  │ Error: error creating S3 bucket ACL for tomliptrot-ecr-test-main-logs: AccessControlListNotSupported: The bucket does not allow ACLs
  │ 	status code: 400, request id: DRWDABEZYXJ4K199, host id: zBqNGWSehFvaFddGFHJSNV0xDDH2qxpm77rT/BCvYPQWmrS4xYyDSO9Kw7QVprJ4MG0yOxMEJ6w=
  │ 
  │   with aws_s3_bucket_acl.lb_access_logs_acl,
  │   on elb.tf line 34, in resource "aws_s3_bucket_acl" "lb_access_logs_acl":
  │   34: resource "aws_s3_bucket_acl" "lb_access_logs_acl" {
  │ 
  ╵
  ╷
  │ Error: [WARN] A duplicate Security Group rule was found on (sg-001cc849fc8aa34ee). This may be
  │ a side effect of a now-fixed Terraform issue causing two security groups with
  │ identical attributes but different source_security_group_ids to overwrite each
  │ other in the state. See https://github.com/hashicorp/terraform/pull/2376 for more
  │ information and instructions for recovery. Error: InvalidPermission.Duplicate: the specified rule "peer: 0.0.0.0/0, TCP, from port: 80, to port: 80, ALLOW" already exists
  │ 	status code: 400, request id: 29370e41-b44c-4576-aa45-af3edb17fdd1
  │ 
  │   with aws_security_group_rule.ingress_http,
  │   on security-group.tf line 21, in resource "aws_security_group_rule" "ingress_http":
  │   21: resource "aws_security_group_rule" "ingress_http" {
  │ 
  ╵
  2023-06-13 09:05:12,029 root         WARNING 
  ~#~#~#~DEPLOYING OPS REPO [terraform] FAILED~#~#~#~
Error: Process completed with exit code 1.
```

Any suggestions?
